env: python
pythonVersion: 3.10


services:
  - type: web
    name: scalping-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars: []
